### ISSUE TITLE
Default values should be initializable without a proc.

### ISSUE THREAD

**Issue by archseer** [polyfox/moon-data_model#1]
Do a `dup` on the default values, that way we get rid of the string mutability issues.

**Comment by IceDragon200** [comment]
@archSeer You are really bent hell on this feature huh, I hope you are aware that not every obj can be `dup`-ed (`Numeric`, `Symbol`), how do you suggest we deal with this issue?

**Comment by archseer** [comment]
How about '.try(:dup) || obj'? I just want to make default strings simpler,
a proc really shouldn't be necessary.
